# Generated by Django 2.2.4 on 2019-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_child_leader_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='jonjomeutunos@gmail.com', max_length=254),
        ),
    ]
