# Generated by Django 2.2.4 on 2019-08-25 18:09

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190825_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/static/users/img/photos/', validators=[users.models.validate_img_extension], verbose_name='Photo'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
