# Generated by Django 2.2.4 on 2019-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='score',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
    ]
