# Generated by Django 2.2.4 on 2019-08-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190826_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Test'),
        ),
    ]
