# Generated by Django 2.2.4 on 2019-08-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_userresponse_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.AddField(
            model_name='test',
            name='aplicate',
            field=models.DateField(blank=True, null=True, verbose_name='Aplication'),
        ),
        migrations.AddField(
            model_name='test',
            name='create',
            field=models.DateField(auto_now=True, verbose_name='Creation'),
        ),
        migrations.AlterField(
            model_name='manypropositionquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='many_proposition_answer', to='tournament.GroupProposition'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiple_choice_answer', to='tournament.Proposition'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_question_answer', to='tournament.Proposition'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, related_name='from_test', to='tournament.Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.FloatField(default=1.0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='sumtypequestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sum_type_answer', to='tournament.IntegerProposition'),
        ),
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='thema',
            field=models.CharField(default='', max_length=30, verbose_name='Thema'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_or_false_answer', to='tournament.BooleanProposition'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_or_false_proposition', to='tournament.Proposition'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Proposition'),
        ),
    ]
