# Generated by Django 2.2.4 on 2019-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20190826_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='desc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(related_name='from_test', to='tournament.Test'),
        ),
    ]
