# Generated by Django 2.2.4 on 2019-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20190826_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='PROPOSITION_TYPE',
            field=models.CharField(default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='question',
            name='QUESTION_TYPE',
            field=models.CharField(default='GEN', max_length=3),
        ),
    ]
