# Generated by Django 2.2.4 on 2019-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190826_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='PROPOSITION_TYPE',
            field=models.CharField(choices=[('INT', 'Integer Number'), ('TXT', 'Text'), ('FLT', 'Float Number'), ('BOL', 'Boolean'), ('GRP', 'Group')], default='GEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='QUESTION_TYPE',
            field=models.CharField(choices=[('CHO', 'Multiple Choice'), ('TOF', 'True or False'), ('OPN', 'Open'), ('SUM', 'Summation'), ('PRO', 'Multiple Propositions'), ('GRP', 'Group')], default='GEN', max_length=3),
        ),
    ]
